name: Build and upload resume
on:
  create:
  workflow_dispatch:
  push:
    branches: [master]
env:
  IMAGE_NAME: resume-image:${{github.sha}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.IMAGE_NAME }}
      - name: Build the Resume
        run: docker run --rm -v ${PWD}:/home/app/resume ${{env.IMAGE_NAME}} EXPORT_DIR=output/resume html pdf export
      - name: Upload HTML
        uses: actions/upload-artifact@v4
        with:
          name: resume.html
          path: output/resume/resume.html
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume.pdf
          path: output/resume/resume.pdf
